<?php
$text = "
biegać laufen läuft lief gelaufen\"
brać nehmen nimmt nahm genommen\"
być sein ist war gewesen\"
chcieć wollen will wollte gewollt\"
cierpieć leiden litt gelitten\"
ciągnąć ziehen zog gezogen\"
ciąć schneiden schnitt geschnitten\"
czynić tun tut tat getan\"
dawać geben gibt gab gegeben\"
drzeć reißen riss gerissen\"
gubić verlieren verlor verloren\"
iść gehen ging gegangen\"
jechać fahren fährt fuhr gefahren\"
jeść essen isst aß gegessen\"
jeździć konno reiten ritt geritten\"
kraść stehlen stiehlt stahl gestohlen\"
krzyczeć schreien schrie geschrien\"
kłamać lügen log gelogen\"
kłócić się streiten stritt gestritten\"
latać fliegen, fliegt, flog, ist geflogen\"
leżeć liegen lag gelegen\"
lubić mögen mag mochte gemocht\"
marznąć frieren fror gefroren\"
mierzyć messen misst maß gemessen\"
mieć haben hat hatte gehabt\"
mieć powinność sollen soll sollte gesollt\"
mieć pozwolenie dürfen darf durfte hat gedurft\"
milczeć schweigen schwieg geschwiegen\"
musieć müssen muss musste gemusst\"
myć waschen wäscht wusch gewaschen\"
myśleć denken denkt dachte hat gedacht\"
móc können kann konnte gekonnt\"
mówić sprechen spricht sprach gesprochen\"
nazywać nennen nannte genannt\"
nazywać się heißen hieß geheißen\"
nosić tragen trägt trug getragen\"
oferować bieten, bietet, bot, hat geboten opadać\"
patrzeć sehen sieht sah gesehen\"
piec braten, brät, briet, hat gebraten\"
pisać schreiben schrieb geschrieben\"
pić trinken trank getrunken\"
podnosić heben hob gehoben\"
podnosić się steigen stieg gestiegen\"
podobać się gefallen gefällt gefiel gefallen\"
polecać empfehlen empfiehlt empfahl empfohlen\"
pomagać helfen hilft half geholfen\"
popychać stoßen stößt stieß gestoßen\"
pozwalać lassen lässt ließ gelassen\"
pożyczać leihen lieh geliehen\"
prosić bitten bat gebeten\"
przychodzić kommen kam gekommen\"
przynosić bringen bringt brachte hat gebracht\"
pędzić rennen rannte gerannt\"
płynąć fließen floss geflossen\"
pływać schwimmen schwamm geschwommen\"
radzić raten rät riet geraten\"
rosnąć wachsen wächst wuchs gewachsen\"
rozkazywać befehlen befiehlt befahl befohlen\"
rozkoszować się genießen genoss genossen\"
rzucać werfen wirft warf geworfen\"
siedzieć sitzen saß gesessen\"
sięgać greifen griff gegriffen\"
skakać springen sprang gesprungen\"
spać schlafen schläft schlief geschlafen\"
spotykać treffen trifft traf getroffen\"
stać stehen stand gestanden\"
trzeć reiben rieb gerieben\"
trzymać halten hält hielt gehalten\"
tworzyć schaffen schuf geschaffen\"
udać się gelingen gelang gelungen\"
umierać sterben stirbt starb gestorben\"
ważyć wiegen wog gewogen\"
wiedzieć wissen weiß wusste gewusst\"
wołać rufen rief gerufen\"
wydarzyć się geschehen geschieht geschah geschehen\"
wygrywać gewinnen gewann gewonnen\"
zaczynać się beginnen begann begonnen\"
zamykać schließen schloss geschlossen\"
zapominać vergessen vergisst vergaß vergessen\"
zmuszać zwingen zwang gezwungen\"
znajdować finden, findet, fand, hat gefunden\"
znać kennen kannte gekannt\"
zostawać bleiben blieb geblieben\"
zostać werden wird wurde geworden\"
ładować laden lädt lud geladen\"
łapać fangen fängt fing hat gefangen\"
śpiewać singen sang gesungen\"";

function str_replace_first($from, $to, $content)
{
    $from = '/'.preg_quote($from, '/').'/';

    return preg_replace($from, $to, $content, 1);
}

foreach(preg_split("/((\r?\n)|(\r\n?))/", $text) as $line){
    echo str_replace_first(" ", ':"', $line).",<br>";
} 